create table if not exists oauth2_registered_client (
  id varchar(100) not null,
  client_id varchar(100) not null,
  client_id_issued_at timestamp not null default current_timestamp,
  client_secret varchar(200) default null,
  client_secret_expires_at timestamp null default null,
  client_name varchar(200) not null,
  client_authentication_methods varchar(1000) not null,
  authorization_grant_types varchar(1000) not null,
  redirect_uris varchar(1000) default null,
  post_logout_redirect_uris varchar(1000) default null,
  scopes varchar(1000) not null,
  client_settings varchar(2000) not null,
  token_settings varchar(2000) not null,
  primary key (id),
  unique key uk_oauth2_registered_client_client_id (client_id)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists oauth2_authorization (
  id varchar(100) not null,
  registered_client_id varchar(100) not null,
  principal_name varchar(200) not null,
  authorization_grant_type varchar(100) not null,
  authorized_scopes varchar(1000) default null,
  attributes blob default null,
  state varchar(500) default null,
  authorization_code_value blob default null,
  authorization_code_issued_at timestamp null default null,
  authorization_code_expires_at timestamp null default null,
  authorization_code_metadata blob default null,
  access_token_value blob default null,
  access_token_issued_at timestamp null default null,
  access_token_expires_at timestamp null default null,
  access_token_metadata blob default null,
  access_token_type varchar(100) default null,
  access_token_scopes varchar(1000) default null,
  oidc_id_token_value blob default null,
  oidc_id_token_issued_at timestamp null default null,
  oidc_id_token_expires_at timestamp null default null,
  oidc_id_token_metadata blob default null,
  refresh_token_value blob default null,
  refresh_token_issued_at timestamp null default null,
  refresh_token_expires_at timestamp null default null,
  refresh_token_metadata blob default null,
  user_code_value blob default null,
  user_code_issued_at timestamp null default null,
  user_code_expires_at timestamp null default null,
  user_code_metadata blob default null,
  device_code_value blob default null,
  device_code_issued_at timestamp null default null,
  device_code_expires_at timestamp null default null,
  device_code_metadata blob default null,
  primary key (id),
  key idx_oauth2_authorization_registered_client_id (registered_client_id),
  key idx_oauth2_authorization_principal_name (principal_name)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;

create table if not exists oauth2_authorization_consent (
  registered_client_id varchar(100) not null,
  principal_name varchar(200) not null,
  authorities varchar(1000) not null,
  primary key (registered_client_id, principal_name)
) engine=InnoDB default charset=utf8mb4 collate=utf8mb4_unicode_ci;
