package com.minitiktok.auth;

import java.util.List;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.test.web.servlet.MockMvc;

import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.jwt;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@AutoConfigureMockMvc
@SpringBootTest
class AuthBackendApplicationTests {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUpUsersTable() {
        jdbcTemplate.execute("""
                create table if not exists users (
                  id bigint generated by default as identity primary key,
                  username varchar(64) not null unique,
                  password_hash varchar(255) not null,
                  enabled boolean not null default true,
                  created_at timestamp not null default current_timestamp,
                  updated_at timestamp not null default current_timestamp
                )
                """);
        jdbcTemplate.update("delete from users");
    }

    @Test
    void contextLoads() {
    }

    @Test
    void jwksEndpointReturnsPublicKeySet() throws Exception {
        mockMvc.perform(get("/oauth2/jwks"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.keys").isArray());
    }

    @Test
    void thirdPartyResourceReturnsProfileWithReadScope() throws Exception {
        mockMvc.perform(get("/third-party/resources/me")
                        .with(jwt().jwt(jwt -> jwt
                                .subject("1")
                                .claim("preferred_username", "demo")
                                .claim("scope", List.of("video:read")))
                                .authorities(new SimpleGrantedAuthority("SCOPE_video:read"))))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.provider").value("mini-tiktok-mock"))
                .andExpect(jsonPath("$.data.userId").value("1"))
                .andExpect(jsonPath("$.data.username").value("demo"));
    }

    @Test
    void thirdPartyWriteResourceRequiresWriteScope() throws Exception {
        mockMvc.perform(post("/third-party/resources/videos")
                        .with(jwt().jwt(jwt -> jwt
                                .subject("1")
                                .claim("preferred_username", "demo")
                                .claim("scope", List.of("video:read")))
                                .authorities(new SimpleGrantedAuthority("SCOPE_video:read"))))
                .andExpect(status().isForbidden());
    }

    @Test
    void jsonRegisterCreatesUser() throws Exception {
        mockMvc.perform(post("/api/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {"username":"jsonuser","password":"Secret123"}
                                """))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200))
                .andExpect(jsonPath("$.data.id").isNumber())
                .andExpect(jsonPath("$.data.username").value("jsonuser"));
    }

    @Test
    void jsonRegisterRejectsDuplicateUsername() throws Exception {
        mockMvc.perform(post("/api/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {"username":"dupeuser","password":"Secret123"}
                                """))
                .andExpect(status().isOk());

        mockMvc.perform(post("/api/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {"username":"dupeuser","password":"Secret123"}
                                """))
                .andExpect(status().isConflict())
                .andExpect(jsonPath("$.code").value(409));
    }

    @Test
    void jsonRegisterRejectsInvalidPayload() throws Exception {
        mockMvc.perform(post("/api/register")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content("""
                                {"username":"ab","password":"123"}
                                """))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.code").value(400));
    }
}
