package com.minitiktok.auth;

import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.Duration;
import java.util.Base64;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.minitiktok.auth.security.AuthUserPrincipal;
import com.minitiktok.auth.service.UserService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.http.MediaType;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.security.oauth2.core.AuthorizationGrantType;
import org.springframework.security.oauth2.core.ClientAuthenticationMethod;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.jwt.JwtDecoder;
import org.springframework.security.oauth2.server.authorization.client.RegisteredClient;
import org.springframework.security.oauth2.server.authorization.client.RegisteredClientRepository;
import org.springframework.security.oauth2.server.authorization.settings.ClientSettings;
import org.springframework.security.oauth2.server.authorization.settings.TokenSettings;
import org.springframework.mock.web.MockHttpSession;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.web.util.UriComponentsBuilder;

import static org.assertj.core.api.Assertions.assertThat;
import static org.hamcrest.Matchers.containsString;
import static org.hamcrest.Matchers.equalTo;
import static org.hamcrest.Matchers.startsWith;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.csrf;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.jwt;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.options;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.header;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.jsonPath;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.model;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.redirectedUrl;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.view;

@AutoConfigureMockMvc
@SpringBootTest
class AuthBackendApplicationTests {

    private static final String DEMO_PASSWORD = "Demo@123456";
    private static final String DEMO_PASSWORD_HASH =
            "$2y$10$NWdd7X01kXSvQMCYKgjfpujxSBVsnY/croLh3O8KsrG8Qb0YkWZWa";
    private static final String REDIRECT_URI = "http://localhost:5173/oauth/callback";
    private static final String FRONTEND_BASE_URL = "http://localhost:5173";

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private JdbcTemplate jdbcTemplate;

    @Autowired
    private PasswordEncoder passwordEncoder;

    @Autowired
    private UserService userService;

    @Autowired
    private RegisteredClientRepository registeredClientRepository;

    @Autowired
    private JwtDecoder jwtDecoder;

    @Autowired
    private ObjectMapper objectMapper;

    @BeforeEach
    void setUpDatabase() {
        jdbcTemplate.execute("""
                create table if not exists users (
                  id bigint generated by default as identity primary key,
                  username varchar(64) not null unique,
                  password_hash varchar(255) not null,
                  enabled boolean not null default true,
                  created_at timestamp not null default current_timestamp,
                  updated_at timestamp not null default current_timestamp
                )
                """);
        jdbcTemplate.execute("""
                create table if not exists oauth2_registered_client (
                  id varchar(100) not null primary key,
                  client_id varchar(100) not null unique,
                  client_id_issued_at timestamp not null default current_timestamp,
                  client_secret varchar(200) default null,
                  client_secret_expires_at timestamp null default null,
                  client_name varchar(200) not null,
                  client_authentication_methods varchar(1000) not null,
                  authorization_grant_types varchar(1000) not null,
                  redirect_uris varchar(1000) default null,
                  post_logout_redirect_uris varchar(1000) default null,
                  scopes varchar(1000) not null,
                  client_settings varchar(2000) not null,
                  token_settings varchar(2000) not null
                )
                """);
        jdbcTemplate.execute("""
                create table if not exists oauth2_authorization (
                  id varchar(100) not null primary key,
                  registered_client_id varchar(100) not null,
                  principal_name varchar(200) not null,
                  authorization_grant_type varchar(100) not null,
                  authorized_scopes varchar(1000) default null,
                  attributes blob default null,
                  state varchar(500) default null,
                  authorization_code_value blob default null,
                  authorization_code_issued_at timestamp null default null,
                  authorization_code_expires_at timestamp null default null,
                  authorization_code_metadata blob default null,
                  access_token_value blob default null,
                  access_token_issued_at timestamp null default null,
                  access_token_expires_at timestamp null default null,
                  access_token_metadata blob default null,
                  access_token_type varchar(100) default null,
                  access_token_scopes varchar(1000) default null,
                  oidc_id_token_value blob default null,
                  oidc_id_token_issued_at timestamp null default null,
                  oidc_id_token_expires_at timestamp null default null,
                  oidc_id_token_metadata blob default null,
                  refresh_token_value blob default null,
                  refresh_token_issued_at timestamp null default null,
                  refresh_token_expires_at timestamp null default null,
                  refresh_token_metadata blob default null,
                  user_code_value blob default null,
                  user_code_issued_at timestamp null default null,
                  user_code_expires_at timestamp null default null,
                  user_code_metadata blob default null,
                  device_code_value blob default null,
                  device_code_issued_at timestamp null default null,
                  device_code_expires_at timestamp null default null,
                  device_code_metadata blob default null
                )
                """);
        jdbcTemplate.execute("""
                create table if not exists oauth2_authorization_consent (
                  registered_client_id varchar(100) not null,
                  principal_name varchar(200) not null,
                  authorities varchar(1000) not null,
                  primary key (registered_client_id, principal_name)
                )
                """);
        jdbcTemplate.update("delete from oauth2_authorization_consent");
        jdbcTemplate.update("delete from oauth2_authorization");
        jdbcTemplate.update("delete from oauth2_registered_client");
        jdbcTemplate.update("delete from users");
        registeredClientRepository.save(tiktokWebClient());
    }

    @Test
    void contextLoads() {
    }

    @Test
    void jwksEndpointReturnsPublicKeySet() throws Exception {
        mockMvc.perform(get("/oauth2/jwks"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.keys").isArray());
    }

    @Test
    void healthEndpointIsPublic() throws Exception {
        mockMvc.perform(get("/health"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200))
                .andExpect(jsonPath("$.data.status").value("ok"));
    }

    @Test
    void wellKnownAuthorizationServerMetadataIsPublic() throws Exception {
        mockMvc.perform(get("/.well-known/oauth-authorization-server"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.issuer").value("http://localhost:9000"))
                .andExpect(jsonPath("$.authorization_endpoint").value("http://localhost:9000/oauth2/authorize"))
                .andExpect(jsonPath("$.token_endpoint").value("http://localhost:9000/oauth2/token"))
                .andExpect(jsonPath("$.jwks_uri").value("http://localhost:9000/oauth2/jwks"));
    }

    @Test
    void loginPageRendersStatusMessagesAndCsrfField() throws Exception {
        mockMvc.perform(get("/login")
                        .queryParam("registered", "")
                        .queryParam("logout", "")
                        .queryParam("error", ""))
                .andExpect(status().isOk())
                .andExpect(view().name("login"))
                .andExpect(content().string(containsString("Mini-Tiktok 登录")))
                .andExpect(content().string(containsString("注册成功，请登录。")))
                .andExpect(content().string(containsString("已退出登录。")))
                .andExpect(content().string(containsString("用户名或密码错误。")))
                .andExpect(content().string(containsString("name=\"_csrf\"")));
    }

    @Test
    void registerPageRendersEmptyFormWithCsrfField() throws Exception {
        mockMvc.perform(get("/register"))
                .andExpect(status().isOk())
                .andExpect(view().name("register"))
                .andExpect(model().attributeExists("registerRequest"))
                .andExpect(content().string(containsString("创建账号")))
                .andExpect(content().string(containsString("name=\"_csrf\"")));
    }

    @Test
    void databaseConnectionAndLookupsWork() {
        Integer probe = jdbcTemplate.queryForObject("select 1", Integer.class);
        assertThat(probe).isEqualTo(1);

        jdbcTemplate.update("""
                        insert into users (username, password_hash, enabled, created_at, updated_at)
                        values (?, ?, true, current_timestamp, current_timestamp)
                        """,
                "lookupuser",
                passwordEncoder.encode("Secret123"));

        assertThat(userService.findByUsername("lookupuser"))
                .isPresent()
                .get()
                .satisfies(user -> {
                    assertThat(user.getId()).isNotNull();
                    assertThat(user.getUsername()).isEqualTo("lookupuser");
                    assertThat(passwordEncoder.matches("Secret123", user.getPasswordHash())).isTrue();
                });

        RegisteredClient client = registeredClientRepository.findByClientId("tiktok-web");
        assertThat(client).isNotNull();
        assertThat(client.getAuthorizationGrantTypes()).contains(AuthorizationGrantType.AUTHORIZATION_CODE);
        assertThat(client.getClientAuthenticationMethods()).contains(ClientAuthenticationMethod.NONE);
        assertThat(client.getClientSettings().isRequireProofKey()).isTrue();
    }

    @Test
    void authorizationCodePkceFlowIssuesJwtWithExpectedClaims() throws Exception {
        String codeVerifier = "review-test-code-verifier-with-enough-entropy-1234567890";
        String codeChallenge = s256CodeChallenge(codeVerifier);

        String location = mockMvc.perform(get("/oauth2/authorize")
                        .queryParam("response_type", "code")
                        .queryParam("client_id", "tiktok-web")
                        .queryParam("redirect_uri", REDIRECT_URI)
                        .queryParam("scope", "video:read video:write")
                        .queryParam("state", "review-state")
                        .queryParam("code_challenge", codeChallenge)
                        .queryParam("code_challenge_method", "S256")
                        .with(user(new AuthUserPrincipal(1L, "demo", DEMO_PASSWORD_HASH, true))))
                .andExpect(status().is3xxRedirection())
                .andExpect(header().string("Location", startsWith(REDIRECT_URI)))
                .andExpect(header().string("Location", containsString("state=review-state")))
                .andReturn()
                .getResponse()
                .getHeader("Location");

        String code = UriComponentsBuilder.fromUriString(location)
                .build()
                .getQueryParams()
                .getFirst("code");

        String tokenResponse = mockMvc.perform(post("/oauth2/token")
                        .contentType(MediaType.APPLICATION_FORM_URLENCODED)
                        .param("grant_type", "authorization_code")
                        .param("client_id", "tiktok-web")
                        .param("redirect_uri", REDIRECT_URI)
                        .param("code", code)
                        .param("code_verifier", codeVerifier))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.access_token").isString())
                .andExpect(jsonPath("$.token_type").value("Bearer"))
                .andReturn()
                .getResponse()
                .getContentAsString();

        String accessToken = objectMapper.readTree(tokenResponse)
                .get("access_token")
                .asText();
        Jwt jwt = jwtDecoder.decode(accessToken);
        assertThat(jwt.getIssuer().toString()).isEqualTo("http://localhost:9000");
        assertThat(jwt.getSubject()).isEqualTo("1");
        assertThat(jwt.getClaimAsString("preferred_username")).isEqualTo("demo");
        assertThat(jwt.getClaimAsStringList("scope")).containsExactlyInAnyOrder("video:read", "video:write");
    }

    @Test
    void unauthenticatedAuthorizeRequestReturnsToAuthorizationAfterLogin() throws Exception {
        jdbcTemplate.update("""
                        insert into users (username, password_hash, enabled, created_at, updated_at)
                        values (?, ?, true, current_timestamp, current_timestamp)
                        """,
                "demo",
                DEMO_PASSWORD_HASH);
        String codeVerifier = "review-test-code-verifier-with-enough-entropy-1234567890";
        String codeChallenge = s256CodeChallenge(codeVerifier);

        MvcResult authorizeResult = mockMvc.perform(get("/oauth2/authorize")
                        .queryParam("response_type", "code")
                        .queryParam("client_id", "tiktok-web")
                        .queryParam("redirect_uri", REDIRECT_URI)
                        .queryParam("scope", "video:read video:write")
                        .queryParam("state", "review-state")
                        .queryParam("code_challenge", codeChallenge)
                        .queryParam("code_challenge_method", "S256")
                        .accept(MediaType.TEXT_HTML))
                .andExpect(status().is3xxRedirection())
                .andExpect(header().string("Location", containsString("/login")))
                .andReturn();

        MockHttpSession session = (MockHttpSession) authorizeResult.getRequest().getSession(false);
        assertThat(session).isNotNull();

        mockMvc.perform(post("/login")
                        .session(session)
                        .with(csrf())
                        .param("username", "demo")
                        .param("password", DEMO_PASSWORD))
                .andExpect(status().is3xxRedirection())
                .andExpect(header().string("Location", containsString("/oauth2/authorize")))
                .andExpect(header().string("Location", containsString("client_id=tiktok-web")))
                .andExpect(header().string("Location", containsString("state=review-state")));
    }

    @Test
    void formRegisterCreatesUserAndRedirectsToLogin() throws Exception {
        mockMvc.perform(post("/register")
                        .with(csrf())
                        .param("username", "formuser")
                        .param("password", "Secret123"))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/login?registered"));

        Integer count = jdbcTemplate.queryForObject(
                "select count(*) from users where username = ?",
                Integer.class,
                "formuser");
        assertThat(count).isEqualTo(1);

        String passwordHash = jdbcTemplate.queryForObject(
                "select password_hash from users where username = ?",
                String.class,
                "formuser");
        assertThat(passwordHash).isNotEqualTo("Secret123");
        assertThat(passwordHash).startsWith("$2");
        assertThat(passwordEncoder.matches("Secret123", passwordHash)).isTrue();
    }

    @Test
    void formRegisterWithContinueRedirectsBackToAuthorizationEndpoint() throws Exception {
        String continueUrl = "/oauth2/authorize?response_type=code&client_id=tiktok-web";

        mockMvc.perform(post("/register")
                        .with(csrf())
                        .param("username", "oauthregister")
                        .param("password", "Secret123")
                        .param("continue", continueUrl))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl(continueUrl));

        Integer count = jdbcTemplate.queryForObject(
                "select count(*) from users where username = ?",
                Integer.class,
                "oauthregister");
        assertThat(count).isEqualTo(1);
    }

    @Test
    void formRegisterIgnoresExternalContinueUrl() throws Exception {
        mockMvc.perform(post("/register")
                        .with(csrf())
                        .param("username", "safeuser")
                        .param("password", "Secret123")
                        .param("continue", "https://example.com/oauth2/authorize"))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/login?registered"));
    }

    @Test
    void formRegisterRequiresCsrfToken() throws Exception {
        mockMvc.perform(post("/register")
                        .param("username", "csrfuser")
                        .param("password", "Secret123"))
                .andExpect(status().isForbidden());

        Integer count = jdbcTemplate.queryForObject(
                "select count(*) from users where username = ?",
                Integer.class,
                "csrfuser");
        assertThat(count).isZero();
    }

    @Test
    void formRegisterTrimsUsernameBeforePersisting() throws Exception {
        mockMvc.perform(post("/register")
                        .with(csrf())
                        .param("username", "  trimuser  ")
                        .param("password", "Secret123"))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/login?registered"));

        Integer trimmedCount = jdbcTemplate.queryForObject(
                "select count(*) from users where username = ?",
                Integer.class,
                "trimuser");
        Integer rawCount = jdbcTemplate.queryForObject(
                "select count(*) from users where username = ?",
                Integer.class,
                "  trimuser  ");
        assertThat(trimmedCount).isEqualTo(1);
        assertThat(rawCount).isZero();
    }

    @Test
    void formRegisterAcceptsUsernameAndPasswordAtValidationBoundaries() throws Exception {
        String username = "u".repeat(32);
        String password = "p".repeat(64);

        mockMvc.perform(post("/register")
                        .with(csrf())
                        .param("username", username)
                        .param("password", password))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/login?registered"));

        String passwordHash = jdbcTemplate.queryForObject(
                "select password_hash from users where username = ?",
                String.class,
                username);
        assertThat(passwordEncoder.matches(password, passwordHash)).isTrue();
    }

    @Test
    void formRegisterRejectsDuplicateUsername() throws Exception {
        mockMvc.perform(post("/register")
                        .with(csrf())
                        .param("username", "dupeuser")
                        .param("password", "Secret123"))
                .andExpect(status().is3xxRedirection());

        mockMvc.perform(post("/register")
                        .with(csrf())
                        .param("username", "dupeuser")
                        .param("password", "Secret123"))
                .andExpect(status().isOk())
                .andExpect(view().name("register"))
                .andExpect(model().attribute("registerError", equalTo("用户名已存在")));
    }

    @Test
    void formRegisterRejectsInvalidPayload() throws Exception {
        mockMvc.perform(post("/register")
                        .with(csrf())
                        .param("username", "ab")
                        .param("password", "123"))
                .andExpect(status().isOk())
                .andExpect(view().name("register"))
                .andExpect(model().attributeHasFieldErrors("registerRequest", "username", "password"));
    }

    @Test
    void formRegisterRejectsBlankPayload() throws Exception {
        mockMvc.perform(post("/register")
                        .with(csrf())
                        .param("username", "   ")
                        .param("password", ""))
                .andExpect(status().isOk())
                .andExpect(view().name("register"))
                .andExpect(model().attributeHasFieldErrors("registerRequest", "username", "password"));
    }

    @Test
    void formRegisterRejectsValuesAboveMaximumLength() throws Exception {
        mockMvc.perform(post("/register")
                        .with(csrf())
                        .param("username", "u".repeat(33))
                        .param("password", "p".repeat(65)))
                .andExpect(status().isOk())
                .andExpect(view().name("register"))
                .andExpect(model().attributeHasFieldErrors("registerRequest", "username", "password"));
    }

    @Test
    void demoUserCanLoginWithBcryptPassword() throws Exception {
        jdbcTemplate.update("""
                        insert into users (username, password_hash, enabled, created_at, updated_at)
                        values (?, ?, true, current_timestamp, current_timestamp)
                        """,
                "demo",
                DEMO_PASSWORD_HASH);

        assertThat(passwordEncoder.matches(DEMO_PASSWORD, DEMO_PASSWORD_HASH)).isTrue();

        mockMvc.perform(post("/login")
                        .with(csrf())
                        .param("username", "demo")
                        .param("password", DEMO_PASSWORD))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl(FRONTEND_BASE_URL));
    }

    @Test
    void loginWithWrongPasswordRedirectsToLoginError() throws Exception {
        insertUser("demo", DEMO_PASSWORD_HASH, true);

        mockMvc.perform(post("/login")
                        .with(csrf())
                        .param("username", "demo")
                        .param("password", "wrong-password"))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/login?error"));
    }

    @Test
    void disabledUserCannotLogin() throws Exception {
        insertUser("disabled", DEMO_PASSWORD_HASH, false);

        mockMvc.perform(post("/login")
                        .with(csrf())
                        .param("username", "disabled")
                        .param("password", DEMO_PASSWORD))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl("/login?error"));
    }

    @Test
    void loginRequiresCsrfToken() throws Exception {
        insertUser("demo", DEMO_PASSWORD_HASH, true);

        mockMvc.perform(post("/login")
                        .param("username", "demo")
                        .param("password", DEMO_PASSWORD))
                .andExpect(status().isForbidden());
    }

    @Test
    void getLogoutClearsSessionCookieAndReturnsToFrontend() throws Exception {
        mockMvc.perform(get("/logout")
                        .with(user("demo")))
                .andExpect(status().is3xxRedirection())
                .andExpect(redirectedUrl(FRONTEND_BASE_URL))
                .andExpect(header().string("Set-Cookie", containsString("JSESSIONID=;")));
    }

    @Test
    void usersMeRequiresAuthentication() throws Exception {
        mockMvc.perform(get("/users/me"))
                .andExpect(status().is3xxRedirection())
                .andExpect(header().string("Location", containsString("/login")));
    }

    @Test
    void usersMeReturnsAuthUserPrincipalProfile() throws Exception {
        mockMvc.perform(get("/users/me")
                        .with(user(new AuthUserPrincipal(42L, "principaluser", DEMO_PASSWORD_HASH, true))))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200))
                .andExpect(jsonPath("$.data.id").value(42))
                .andExpect(jsonPath("$.data.username").value("principaluser"));
    }

    @Test
    void usersMeReturnsJwtProfile() throws Exception {
        mockMvc.perform(get("/users/me")
                        .with(jwt().jwt(jwt -> jwt
                                .subject("7")
                                .claim("preferred_username", "jwtuser"))))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.id").value(7))
                .andExpect(jsonPath("$.data.username").value("jwtuser"));
    }

    @Test
    void usersMeReturnsNullIdWhenJwtSubjectIsNotNumeric() throws Exception {
        mockMvc.perform(get("/users/me")
                        .with(jwt().jwt(jwt -> jwt
                                .subject("not-a-number")
                                .claim("preferred_username", "jwtuser"))))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.id").doesNotExist())
                .andExpect(jsonPath("$.data.username").value("jwtuser"));
    }

    @Test
    void usersMeFallsBackToAuthenticationNameForStandardUser() throws Exception {
        mockMvc.perform(get("/users/me")
                        .with(user("plainuser")))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.data.id").doesNotExist())
                .andExpect(jsonPath("$.data.username").value("plainuser"));
    }

    @Test
    void corsPreflightAllowsFrontendForTokenEndpoint() throws Exception {
        mockMvc.perform(options("/oauth2/token")
                        .header("Origin", FRONTEND_BASE_URL)
                        .header("Access-Control-Request-Method", "POST")
                        .header("Access-Control-Request-Headers", "content-type"))
                .andExpect(status().isOk())
                .andExpect(header().string("Access-Control-Allow-Origin", FRONTEND_BASE_URL))
                .andExpect(header().string("Access-Control-Allow-Credentials", "true"));
    }

    @Test
    void corsPreflightRejectsUnknownOrigin() throws Exception {
        mockMvc.perform(options("/oauth2/token")
                        .header("Origin", "http://evil.example")
                        .header("Access-Control-Request-Method", "POST"))
                .andExpect(status().isForbidden());
    }

    @Test
    void tokenEndpointRejectsInvalidAuthorizationCode() throws Exception {
        mockMvc.perform(post("/oauth2/token")
                        .contentType(MediaType.APPLICATION_FORM_URLENCODED)
                        .param("grant_type", "authorization_code")
                        .param("client_id", "tiktok-web")
                        .param("redirect_uri", REDIRECT_URI)
                        .param("code", "invalid-code")
                        .param("code_verifier", "review-test-code-verifier-with-enough-entropy-1234567890"))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.error").value("invalid_grant"));
    }

    @Test
    void tokenEndpointRejectsWrongPkceVerifier() throws Exception {
        String codeVerifier = "review-test-code-verifier-with-enough-entropy-1234567890";
        String codeChallenge = s256CodeChallenge(codeVerifier);

        String location = mockMvc.perform(get("/oauth2/authorize")
                        .queryParam("response_type", "code")
                        .queryParam("client_id", "tiktok-web")
                        .queryParam("redirect_uri", REDIRECT_URI)
                        .queryParam("scope", "video:read")
                        .queryParam("state", "pkce-state")
                        .queryParam("code_challenge", codeChallenge)
                        .queryParam("code_challenge_method", "S256")
                        .with(user(new AuthUserPrincipal(1L, "demo", DEMO_PASSWORD_HASH, true))))
                .andExpect(status().is3xxRedirection())
                .andReturn()
                .getResponse()
                .getHeader("Location");
        String code = UriComponentsBuilder.fromUriString(location)
                .build()
                .getQueryParams()
                .getFirst("code");

        mockMvc.perform(post("/oauth2/token")
                        .contentType(MediaType.APPLICATION_FORM_URLENCODED)
                        .param("grant_type", "authorization_code")
                        .param("client_id", "tiktok-web")
                        .param("redirect_uri", REDIRECT_URI)
                        .param("code", code)
                        .param("code_verifier", "wrong-verifier-with-enough-entropy-1234567890"))
                .andExpect(status().isBadRequest())
                .andExpect(jsonPath("$.error").value("invalid_grant"));
    }

    private RegisteredClient tiktokWebClient() {
        return RegisteredClient.withId("tiktok-web")
                .clientId("tiktok-web")
                .clientName("Mini-Tiktok Web")
                .clientAuthenticationMethod(ClientAuthenticationMethod.NONE)
                .authorizationGrantType(AuthorizationGrantType.AUTHORIZATION_CODE)
                .redirectUri(REDIRECT_URI)
                .scope("video:read")
                .scope("video:write")
                .scope("video:like")
                .clientSettings(ClientSettings.builder()
                        .requireProofKey(true)
                        .requireAuthorizationConsent(false)
                        .build())
                .tokenSettings(TokenSettings.builder()
                        .accessTokenTimeToLive(Duration.ofHours(2))
                        .authorizationCodeTimeToLive(Duration.ofMinutes(5))
                        .build())
                .build();
    }

    private static String s256CodeChallenge(String codeVerifier) throws Exception {
        byte[] digest = MessageDigest.getInstance("SHA-256")
                .digest(codeVerifier.getBytes(StandardCharsets.US_ASCII));
        return Base64.getUrlEncoder()
                .withoutPadding()
                .encodeToString(digest);
    }

    private void insertUser(String username, String passwordHash, boolean enabled) {
        jdbcTemplate.update("""
                        insert into users (username, password_hash, enabled, created_at, updated_at)
                        values (?, ?, ?, current_timestamp, current_timestamp)
                        """,
                username,
                passwordHash,
                enabled);
    }
}
